# Generated by Django 3.1 on 2020-08-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(max_length=250, unique=True)),
                ('stack', models.ManyToManyField(blank=True, null=True, to='scraping.Tech')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
