# Generated by Django 3.1 on 2020-08-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20200830_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['created_at']},
        ),
    ]
