# Generated by Django 3.1 on 2020-08-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20200830_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['name']},
        ),
    ]
